- name: install v1.18 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.18.18-0
      - kubeadm-1.18.18-0
      - kubectl-1.18.18-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.18
    use_dockerce: true
